# Numpy Practice
### Numpy arrays are very efficient in storing arrays !

___

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,3,4,5]],np.int64)

In [3]:
arr[0]
arr.shape

(1, 4)

In [4]:
arr.dtype

dtype('int64')

In [5]:
zeroarr=np.zeros((3,4))

In [6]:
zeroarr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
rangarr = np.arange(50)

In [8]:
rangarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
lspc = np.linspace(1,6,8)

In [10]:
lspc

array([1.        , 1.71428571, 2.42857143, 3.14285714, 3.85714286,
       4.57142857, 5.28571429, 6.        ])

In [11]:
emp = np.empty((3,4))

In [12]:
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
emplk = np.empty_like(lspc)

array([1.        , 1.71428571, 2.42857143, 3.14285714, 3.85714286,
       4.57142857, 5.28571429, 6.        ])

In [15]:
rangarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
rangarr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
rangarr.reshape(4,20) //Wrong as rangarr contains 50 elements

ValueError: cannot reshape array of size 50 into shape (4,20)

In [18]:
rangarr.shape

(50,)

In [19]:
reshparr = rangarr.reshape(5,10)

In [20]:
reshparr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
reshparr.ravel()  #Converts the arrays back to original 1-d array without rows/columns

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Axis-0(row) , Axis-1(Column) for a 2-D array

In [22]:
x=[[1,2,3],[8,-1,0],[3,1,5]]

In [23]:
x

[[1, 2, 3], [8, -1, 0], [3, 1, 5]]

In [24]:
tmp = np.array(x)

In [25]:
tmp

array([[ 1,  2,  3],
       [ 8, -1,  0],
       [ 3,  1,  5]])

In [26]:
tmp(axis=0)

TypeError: 'numpy.ndarray' object is not callable

In [27]:
argmax=tmp(Axis=0)

TypeError: 'numpy.ndarray' object is not callable

In [28]:
tmp.argmax(axis=0)   # Max index row wise

array([1, 0, 2])

In [30]:
tmp.sum(axis=0)    # Sum Row Wise

array([12,  2,  8])

In [31]:
tmp.sum()  # Total sum of the Array

22

In [32]:
tmp.argsort(axis=1)   // Shows what sorted indexes should have been column wise

array([[0, 1, 2],
       [1, 2, 0],
       [1, 0, 2]])

Matrix operations are possible in Numpy !

In [37]:
tmp +tmp   # Sum can be directly done

array([[ 2,  4,  6],
       [16, -2,  0],
       [ 6,  2, 10]])

In [36]:
tmp.T  # Transpose operatoin in numpy

array([[ 1,  8,  3],
       [ 2, -1,  1],
       [ 3,  0,  5]])

In [43]:
# Iterator for Numpy:
for item in tmp.flat:
    print(item)

1
2
3
8
-1
0
3
1
5


In [44]:
# where an element is present according to a condition
np.where(tmp>5)  # Returns a tupple

(array([1]), array([0]))

In [46]:
np.count(tmp>0)

AttributeError: module 'numpy' has no attribute 'count'